### ISSUE TITLE
Не устанавливается руссификатор!

### ISSUE THREAD

**Issue by Hu4uTa** [DenisMasterHerobrine/RotN-Translation#1]
Из-за отсутствия руссификатора его установка не возможна, пофиксь пжпжпж
![image](https://user-images.githubusercontent.com/48065305/158075592-28f73226-0ce4-4d89-bc4f-44512de16ac5.png)

**Comment by Suiranoil** [comment]
Поддерживаю, пытался сегодня установить, но когда обнаружил, что ничего нет, из окна выйти захотелось, но я переселил себя и теперь пишу этот коммент.

**Comment by FlaxyDev** [comment]
Руссификатор пока вроде как еще не вышел.

**Comment by Turokirill** [comment]
Не стал ждать этого перевода и перевел сам(Машинный перевод). https://github.com/Turokirill/RusRotN.git

**Comment by DenisMasterHerobrine** [comment]
Готово, русификатор ещё сыроват и в бете, но уже существует здесь:
https://github.com/DenisMasterHerobrine/RotN-Translation/releases
